name: "Test Action"

on:
  pull_request:

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.head_ref) }}
  cancel-in-progress: true

jobs:
  create_milestone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: create
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Next
      - run: echo "The number ${{ steps.create.outputs.number }}"
